apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
name: hpc-compute-module

spec:
templates:

```
- name: compute

  inputs:
    parameters:
      - name: command

      - name: partition
        default: "dev-x86"

      - name: cpu
        default: "2"

      - name: memory
        default: "2Gi"

  metadata:
    annotations:
      slurm-job.vk.io/flags: >
        --account=eehpc-dev-2026d02-075x
        --partition={{inputs.parameters.partition}}

  nodeSelector:
    kubernetes.io/hostname: interlink-node

  tolerations:
    - key: virtual-node.interlink/no-schedule
      operator: Exists

  container:
    image: ubuntu:22.04

    command: ["bash", "-c"]

    args:
      - "{{inputs.parameters.command}}"

    env:
      - name: ARGO_USER
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['workflows.argoproj.io/creator']

    resources:
      requests:
        cpu: "{{inputs.parameters.cpu}}"
        memory: "{{inputs.parameters.memory}}"

      limits:
        cpu: "{{inputs.parameters.cpu}}"
        memory: "{{inputs.parameters.memory}}"
```
