apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: compute-module

spec:
  templates:

  - name: compute

    inputs:
      parameters:
      - name: command

      - name: partition
        default: "dev-x86"

      - name: cpu
        default: "2000m"

      - name: memory
        default: "2Gi"

    metadata:
      annotations:
        slurm-job.vk.io/flags: >
          --account=eehpc-dev-2026d02-075x
          --partition={{inputs.parameters.partition}}
          --cpus-per-task={{inputs.parameters.cpu}}
          --mem={{inputs.parameters.memory}}

    nodeSelector:
      kubernetes.io/hostname: interlink-node

    tolerations:
    - key: virtual-node.interlink/no-schedule
      operator: Exists

    container:
      image: ubuntu:22.04

      command: ["bash", "-c"]

      args:
      - "{{inputs.parameters.command}}"

      env:
      - name: ARGO_USER
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['user']

      resources:
        requests:
          cpu: "1"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
