# Sync dataset directory then reads an existing file and a missing file to test both success and failure cases of the read module.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: default
  generateName: test-02-read-file-
  labels:
    test: "02-read-file"
spec:
  entrypoint: pipeline
  templates:
  - name: pipeline
    dag:
      tasks:
      - name: input-sync
        templateRef:
          namespace: default
          name: sync-module
          template: sync
        arguments:
          parameters:
          - name: input_uri
            value: /users/admin/test-02
          - name: user
            value: admin

      - name: compute-read-success
        dependencies: [input-sync]
        templateRef:
          namespace: default
          name: compute-read-module
          template: compute
        arguments:
          parameters:
          - name: file
            value: /users/admin/test-02/existing-file.txt
          - name: cpu
            value: "2"
          - name: memory
            value: "2Gi"
          - name: user
            value: admin

      - name: compute-read-fail
        dependencies: [input-sync]
        templateRef:
          namespace: default
          name: compute-read-module
          template: compute
        arguments:
          parameters:
          - name: file
            value: /users/admin/case-01/missing-file.txt
          - name: cpu
            value: "2"
          - name: memory
            value: "2Gi"
          - name: user
            value: admin