# Writes files then reads it.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: default
  generateName: test-09-write-read-
  labels:
    test: "09-write-read"
spec:
  entrypoint: pipeline
  templates:
  - name: pipeline
    dag:
      tasks:
      - name: input-sync
        templateRef:
          namespace: default
          name: sync-module
          template: sync
        arguments:
          parameters:
          - name: input_uri
            value: /users/admin/test-09
          - name: user
            value: admin

      - name: compute-write
        dependencies: [input-sync]
        templateRef:
          namespace: default
          name: compute-write-module
          template: compute
        arguments:
          parameters:
          - name: text
            value: "test-09"
          - name: file
            value: /users/admin/test-09/new-file.txt
          - name: cpu
            value: "2"
          - name: memory
            value: "2Gi"
          - name: user
            value: admin

      - name: output-sync
        dependencies: [compute-write]
        templateRef:
          namespace: default
          name: sync-module
          template: sync
        arguments:
          parameters:
          - name: output_uri
            value: /users/admin/test-09
          - name: user
            value: admin

      - name: compute-read
        dependencies: [compute-write]
        templateRef:
          namespace: default
          name: compute-read-module
          template: compute
        arguments:
          parameters:
          - name: file
            value: /users/admin/test-09/new-file.txt
          - name: cpu
            value: "2"
          - name: memory
            value: "2Gi"
          - name: user
            value: admin